import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
          bg-background relative
          before:fixed before:inset-0
          before:bg-[repeating-linear-gradient(45deg,rgb(51,65,85)_0px,rgb(51,65,85)_1px,transparent_1px,transparent_40px)]
          before:opacity-30
          before:-z-10`}
      >
        {children}
      </body>
    </html>
  );
}
